### ISSUE TITLE
`sitegen` plug-in acknowledges `-Dsitegen.sitePort` setting in start-up log message but listens on 8080 regardless

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon-build-tools#1009]
The `sitegen` plug-in seems to support a `sitePort` setting. 

When I run `mvn sitegen:serve -Dsitegen.sitePort=7007` I see
```
[INFO] Site server is up! http://localhost:7007
```
but the server listens on 8080 anyway.

**Comment by romain-grecourt** [comment]
Oops, good catch ! https://github.com/helidon-io/helidon-build-tools/blob/4.0.3/maven-plugins/sitegen-maven-plugin/src/main/java/io/helidon/build/maven/sitegen/SiteServer.java#L55
