### ISSUE TITLE
Update the archetype schema to match the runtime behaviour

### ISSUE THREAD

**Issue by tvallin** [helidon-io/helidon-build-tools#1068]
Fix the schema to document if attribute on `exec` element

```xml
<exec src="foo" if="${bar}"/>
```

Investigate if `if` attributes are supported on all invocation directive in the runtime, if so update the schema accordingly. 

Publish the updated schema on helidon.io.

---

When using the `if` attribute on exec elements, the schema validation does not fail (version 4.0.11).

Investigate why this does not fail. 

---

Investigate if the following is supported by the runtime: 

```xml
<output>
</output>
<exec src="foo"/>
```

If that works update the schema as well.

**Comment by tvallin** [comment]
See https://github.com/helidon-io/helidon-build-tools/issues/749

The condition on invocation is supported at runtime, the schema is up to date but was publish to helidon website.

**Comment by romain-grecourt** [comment]
https://helidon.io/xsd/archetype-2.0.xsd has been updated and now reflects the change.
