### ISSUE TITLE
Expose context values as template model

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon-build-tools#609]
We currently have duplication in our archetypes to expose context value as model.
We need to expose context values as model directly to avoid the duplication.

E.g.
```xml
    <step label="Customize Project">
        <inputs>
            <text name="name" label="Project name" optional="true" default="myproject"/>
            <text name="groupId" label="Project groupId" optional="true" default="com.examples"/>
            <text name="artifactId" label="Project artifactId" optional="true" default="myproject"/>
            <text name="version" label="Project version" optional="true" default="1.0-SNAPSHOT"/>
            <text name="package" label="Java package name" optional="true" default="com.example.myproject"/>
        </inputs>
        <output>
            <model>
                <value key="name">${name}</value>
                <value key="groupId">${groupId}</value>
                <value key="artifactId">${artifactId}</value>
                <value key="project-version">${version}</value>
                <value key="package">${package}</value>
            </model>
        </output>
    </step>
```

I.e we need the ability to use `{{groupId}}` to reference `${groupId}` without having to declare a model value.

Also we currently do not support dot notation as part of the mustache support. It would be a good time to re-visit that and implement support for dot notation in templates.

The dot notation would be useful in order to traverse the model. E.g. `{{foo.bar}}` refers to a map keyed as `foo` that contains a key `bar`.

Also, since this issue is about adding support for context, we should support context paths. This would mean supporting `~` and `..`.

**Comment by aserkes** [comment]
@romain-grecourt, you mentioned : 

> The dot notation would be useful in order to traverse the model. E.g. {{foo.bar}} refers to a map keyed as foo that contains a key bar.
> 
> Also, since this issue is about adding support for context, we should support context paths. This would mean supporting ~ and ...
> 

Does it mean that  {{foo.bar}} with `~` and `..` is planned to be used in mustache templates or it will be used in archetype xml files?

**Comment by romain-grecourt** [comment]
> Does it mean that {{foo.bar}} with `~` and `..` is planned to be used in mustache templates or it will be used in archetype xml files?

In mustache templates.
