### ISSUE TITLE
SimpleXmlParser: Processing instructions are not handled

### ISSUE THREAD

**Issue by ljnelson** [helidon-io/helidon-build-tools#780]
Permitted states do not include [processing instructions](https://www.w3.org/TR/xml/#sec-pi):

https://github.com/oracle/helidon-build-tools/blob/d216b571bb03abd5b08f5a6c65077892e373a871/common/xml/src/main/java/io/helidon/build/common/xml/SimpleXMLParser.java#L226-L239

The manifesting symptom is that in a processing instruction like this:
```xml
<?m2e execute onConfiguration,onIncremental?>
```
…the parser bails out here:

https://github.com/oracle/helidon-build-tools/blob/d216b571bb03abd5b08f5a6c65077892e373a871/common/xml/src/main/java/io/helidon/build/common/xml/SimpleXMLParser.java#L593-L594

**Comment by romain-grecourt** [comment]
Steps to reproduce: 
- generate a quickstart/mp project
- remove `.helidon`
- `helidon dev`
