### ISSUE TITLE
Helidon Web Starter generates only Helidon SE projects

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon-build-tools#797]
https://helidon.io/starter/3.0.1?flavor=mp&step=1&app-type=custom 

generates Helidon SE although MP is selected!

**Comment by romain-grecourt** [comment]
We track issues related to the website internally.

Seems to be a UI bug. If you see this issue again, copy the download link and make sure it matches the selected options.

Note the URL below (`/api/starter`)

```java
curl -o /tmp/project.zip "https://helidon.io/api/starter/3.0.1/generate?flavor=mp&app-type=custom" && \
unzip -p /tmp/project.zip myproject/pom.xml | \
grep '<artifactId>helidon-' | head -1
```
