### ISSUE TITLE
CLI Windows quickstart quits after selecting archetype if user.name contains whitespace

### ISSUE THREAD

**Issue by edbratt** [helidon-io/helidon-build-tools#798]
Common on Windows systems, user name is FIRST\bLAST (\b is space). If this is the setting for user.name, the CLI will bail out after you select the Archetype with (using my user ID: 'Ed Bratt'
`error: default.package.name in C:\Users\Ed Bratt\.helidon\config does not resolve to a valid package name: me.Ed Bratt.mp.quickstart`
I suspect the problem is Ed Bratt in the package name string.
I could get around this by substituting FirstLast into the impacted property settings:
`default.group.id
default.artifact.id`
If possible, this action would be best deferred until after the user had a chance to enter substitute defaults (as occurs when the script continues to completion). Otherwise, the property might need to be modified by removing white-space or substituting underscores.

I wasn't able to substitute user.name as a command-line option (that could have been pilot error)

**Comment by romain-grecourt** [comment]
We should sanitize `user.name`, that's a proper bug.

You can work around this in different ways:
 - update `default.package.name` ~/.helidon/config
 - pass `--package com.example` to the init command
