### ISSUE TITLE
Handlebar copyright comments are not being honored

### ISSUE THREAD

**Issue by trentjeff** [helidon-io/helidon-build-tools#829]
See https://github.com/helidon-io/helidon/pull/5598

The above PR introduces an .hbs file with a copyright comment on the header that should have been found.  However, it resulted in an error:
`
error: Rule copyright failed. Errors:
error:   pico/tools/src/main/java/io/helidon/pico/tools/Item.java:0: Expecting copyright with "13" lines, but it was "empty"
error:   pico/tools/src/test/resources/templates/pico/default/module-info.hbs:1: No comment found

`

**Comment by trentjeff** [comment]
Needed for 4.x builds.

**Comment by trentjeff** [comment]
Once fixed here, we need to remove the .hbs exclusion from https://github.com/helidon-io/helidon/pull/5598/files/b44c3b9172d31bad4e444a3bf0e39a47dfcb969d#diff-cb49f03cb4086001b091019c065d02a38af643b135d1b2f879de098b89435cd5

**Comment by trentjeff** [comment]
@romain-grecourt @barchetta fyi

**Comment by romain-grecourt** [comment]
This is fixed in [master](https://github.com/helidon-io/helidon-build-tools/blob/master/maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/copyright/ValidatorHandlebars.java) and will be included in the upcoming 3.0.2 release.

**Comment by trentjeff** [comment]
Are you also planning to remove the exclusion? If not I can... just need to know..

**Comment by romain-grecourt** [comment]
What exclusion ?

**Comment by romain-grecourt** [comment]
There is nothing to do for this in build-tools except releasing 3.0.2. If we need to track the removal of the copyright exclusion then this should be done in the main repository.
