### ISSUE TITLE
VSCode Helidon:generate fails silently

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon-build-tools#871]
I installed the vscode plugin, and when I execute the `Helidon: generate a new project` nothing happens. I suspect something is wrong in my environment since I also run into #869.

So there seems to be two issues:
1. Something in my environment is causing the extension to fail -- even though it seems as if I have everything I need
2. The failure is silent. I don't see any errors in View->Output

**Comment by aserkes** [comment]
Could you please find in the temporary folder a directory `vscode-helidon` and send me its contain?

**Comment by aserkes** [comment]
Most probably that the problem that is mentioned in #869  is related to the maven plugin helidon-lsp-maven-plugin. The extension uses this plugin for code completion in config files. At the same time this plugin has not been published to the any maven repository yet, so if you do not have it locally such feature as code completion for config files will not work.
So, could you please check your local maven repository ~/.m2/repository/io/helidon/ide-support/lsp does it contain helidon-lsp-maven-plugin`? 
If this plugin is not installed locally I would like to propose you to download helidon-build-projectand build it usingmvn clean install -DskipTestsor just build thehelidon-lsp-maven-plugin` module.

**Comment by barchetta** [comment]
Here is `vscode-helidon` from my TMPDIR: [vscode-helidon.zip](https://github.com/helidon-io/helidon-build-tools/files/10521406/vscode-helidon.zip)

**Comment by aserkes** [comment]
Could you please try this version of the plugin https://github.com/aserkes/helidon-build-tools/suites/10668215597/artifacts/533464333 ? I fixed NPE, added more logs and messages for users. Send me `vscode-helidon` from `TMPDIR` if you have any issues with this version of the plugin.

**Comment by barchetta** [comment]
I now get the error:
```
Cannot get information about Helidon archetypes : Request failed with status code 500
```

Note that I am trying this behind a proxy, so I'm wondering if that is the problem.

[vscode-helidon.zip](https://github.com/helidon-io/helidon-build-tools/files/10551729/vscode-helidon.zip)

**Comment by barchetta** [comment]
Log files attached. Looks like it has something to do with SSL handshake.

[vscode-helidon.zip](https://github.com/helidon-io/helidon-build-tools/files/10560917/vscode-helidon.zip)

**Comment by romain-grecourt** [comment]
Looks like this is caused by Axios not tunneling for proxies, see https://github.com/axios/axios/issues/4531

You can reproduce it with something like this:
```javascript
const axios = require('axios');

axios.get('https://helidon.io/api/versions', {
    proxy: {
        protocol: 'http',
        host: 'proxy.acme.com',
        port: 80
    }
}).then(res => {
    console.log(res)
}).catch(err => {
    console.error(err)
})
```

Axios makes a request with the proxy host as the host and the target URL as `PATH`. This does not work with this corporate proxy.

**Comment by aserkes** [comment]
I replaced Axios.Could you please try this version of the plugin  https://github.com/aserkes/helidon-build-tools/suites/10735978213/artifacts/538481745 ?

**Comment by barchetta** [comment]
Progress, but now get: "Cannot get information about Helidon archetypes : M is not a function".  

From log:

```
message: 'TypeError: M is not a function\n' +
    '    at init (/Users/jdipol/.vscode/extensions/oracle.helidon-3.0.0-SNAPSHOT/target/src/generator.ts:189:56)\n' +
    '    at showHelidonGenerator (/Users/jdipol/.vscode/extensions/oracle.helidon-3.0.0-SNAPSHOT/target/src/generator.ts:418:15)\n' +
    '    at /Users/jdipol/.vscode/extensions/oracle.helidon-3.0.0-SNAPSHOT/target/src/extension.ts:61:9\n' +
    '    at s.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:107622)\n' +
    '    at s.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:108311)\n' +
    '    at u.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:11208)\n' +
    '    at u.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10926)\n' +
```

**Comment by aserkes** [comment]
My bad. Try this - https://github.com/aserkes/helidon-build-tools/suites/10745459240/artifacts/539177112
