### ISSUE TITLE
Add UI for starting a new project 

### ISSUE THREAD

**Issue by hantsy** [helidon-io/helidon-build-tools#89]
Like Quarkus and Spring Initializr, provide a RESTful APIs and UI for developers to generate Helidon projects quickly.

* [Quarkus Code](https://code.quarkus.io/)
* [Spring Initializr](https://start.spring.io)

**Comment by romain-grecourt** [comment]
This may come in the future, however we are focusing one a CLI based experience first.

Once we have figured the proper experience for the CLI (templating, features decoupling etc.) we will consider providing a "starter" UI.

**Comment by romain-grecourt** [comment]
CC @m0mus

**Comment by romain-grecourt** [comment]
See also https://micronaut.io/launch/

**Comment by romain-grecourt** [comment]
Closing as this is now available: https://helidon.io/starter
