### ISSUE TITLE
Handle Jandex 3

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon-build-tools#961]
In Helidon 4 we plan on upgrading Jandex to 3.x. See https://github.com/helidon-io/helidon/issues/6561

It has been reported that in jlink support if it can't read the Jandex index it will re-generate it. This means on a 4.x project it would overwrite the Jandex 3 index with a Jandex 2 index.

We need to either upgrade Jandex support in build-tools to 3.x, or somehow mitigate this issue.

**Comment by romain-grecourt** [comment]
actually the switch to Jandex 3.x was done in https://github.com/helidon-io/helidon-build-tools/pull/956/files ; this is probably incompatible with Helidon 3.x.

We should back-out the update and start a build-tools 4.x branch.

**Comment by tvallin** [comment]
Done by @romain-grecourt in #966 and #973
